[versions]
android-gradle-plugin = "7.4.2"
org-jetbrains-kotlin = "1.8.10"
secrets-gradle-plugin = "2.0.1"

androidx-activity = "1.6.1"
androidx-lifecycle = "2.6.0"
androidx-splashscreen = "1.0.0"
androidx-navigation = "2.5.3"

accompanist = "0.29.1-alpha"

compose = "1.3.3"
compose-compiler = "1.4.2"
material = "1.3.1"
material3 = "1.0.1"

dagger = "2.46"

okhttp = "4.10.0"
retrofit = "2.9.0"

room = "2.5.0"
datastore = "1.0.0"

coil = "2.2.2"

desugar = "1.2.2"
junit = "4.13.2"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-room-core = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

compose-ui-core = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-material-iconscore = { module = "androidx.compose.material:material-icons-core", version.ref = "material" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "material" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }

squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
squareup-okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
google-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
javax-inject = "javax.inject:javax.inject:1"

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# Accompanist
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
google-accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
google-accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
google-accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
google-accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }


[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
com-google-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets-gradle-plugin" }